### ISSUE TITLE
What types of chassis do we support?

### ISSUE THREAD

**Issue by daohu527** [commaai/opendbc#1035]
Do we only support passenger car chassis? We currently have some chassis for teaching and express logistics vehicles. Can these be put into this project? 

At the same time, I suggest making a list to show the appearance of each vehicle. This may be more intuitive. Thank you.

![image](https://github.com/commaai/opendbc/assets/10419854/30b4294f-66a5-4639-aea4-c68e94152169)

**Comment by adeebshihadeh** [comment]
All DBCs are for use in openpilot, so the openpilot car docs are a good indicator of what's applicable.
