### ISSUE TITLE
Licensing terms, dbc files 

### ISSUE THREAD

**Issue by mupfdev** [commaai/opendbc#1058]
Hi there,
I have been working on a tool for CAN and CANopen for some time now. I have also written a simple DBC parser for it.

I have a question: Are the dbc files of this project also under the MIT licence or only opendbc itself?

I would like to publish them bundled with my software, hence the question.

Best regards,
Michael

https://github.com/CANopenTerm/CANopenTerm/issues/32

**Comment by adeebshihadeh** [comment]
To the extent a DBC can be licensed, yeah they're covered.
