### ISSUE TITLE
Toyota Corolla Hybrid: Extremely slow acceleration and early braking when using 'Aggressive' mode

### ISSUE THREAD

**Issue by TKassis** [commaai/opendbc#1161]
### Describe the bug

Aggressive mode seems to be opposite of what it intends to do. Acceleration when the lead starts moving is extremely slow and the car tends to brake way too early when stopping for a lead. I've always had these issues with OpenPilot, but though 'Aggressive' mode would help address them, but for some reason it makes them substantially worse.

### Which car does this affect?

Toyota Corolla Hybrid 2021

### Provide a route where the issue occurs

ecebb0b63434e2f2|2023-06-23--12-14-31--6

### openpilot version

0.9.4

**Comment by sshane** [comment]
Since this issue is mostly about slow acceleration with the more recent reports, going to close as completed by https://github.com/commaai/opendbc/pull/1464!
