### ISSUE TITLE
Revert fingerprint of Toyota Corolla 2021 Hybrid China version

### ISSUE THREAD

**Issue by 0312birdzhang** [commaai/opendbc#1192]
I made a pull a request 2 years ago, https://github.com/commaai/openpilot/pull/25026

However, this car does not have BSM when it leaves the factory, with this fingerprint added,  it causes some same car users not be able to use openpilot normally. Even if the BSM is installed later, there are some models of BSM that cannot be captured by openpilot, like my RV1.

Please delete this line, i'm very sorry.
https://github.com/commaai/opendbc/blob/3a8a8645f61e30ae61ee0f6458c1e34fe53979e5/opendbc/car/toyota/fingerprints.py#L566

I you need BSM error logs, i will provide later.

![b801e37c9fcbb793b683c8bdca744cb](https://github.com/user-attachments/assets/408389af-6487-4851-ba09-e1fe94b7014e)

**Comment by sshane** [comment]
Your car would still match via fuzzy fingerprinting if removed. We also detect BSM via the dynamic fingerprint, what exactly is the problem here? Going to close as this should be a PR

**Comment by 0312birdzhang** [comment]
I have to set `ret.enableBsm` to False, otherwise the log will be full of the following errors.
https://github.com/commaai/opendbc/blob/651be58ac8cd8acaf2754905a78b0c187a99aa25/opendbc/car/toyota/interface.py#L103

![Screenshot from 2024-11-27 16-26-19](https://github.com/user-attachments/assets/53009eb4-b7e3-4431-8e96-e5c15de8d9f6)
(Yes, the screenshot is from a Xiaomi Mi Pad 5 running openpilot)

It has BSM, but it reads empty signals from `0x3F6`.

**Comment by 0312birdzhang** [comment]
> Can you provide a route with rlogs uploaded?

My C3x is on the way, will do it then.

**Comment by 0312birdzhang** [comment]
I would say you are right, removing the fingerprint does not resolve the BSM issues. I'm using a clone C3 now, and my C3x from comma is on the way, will do a upload via connect.comma.ai when i received.

**Comment by 0312birdzhang** [comment]
After rearranging the order of bsm modules and panda, bsm can be detected by openpilot.

![Image](https://github.com/user-attachments/assets/64f9406b-7968-4f4e-b83f-0a87276dba52)
