### ISSUE TITLE
Toyota `GEAR_PACKET_HYBRID.COUNTER` is not actually a counter

### ISSUE THREAD

**Issue by pd0wm** [commaai/opendbc#1328]
Noticed this when making the RAV4 Prime port, and didn't want this information to get lost.

`GEAR_PACKET_HYBRID.COUNTER`, is not actually a counter. It was removed from the RAV4 Prime DBC, but it's still present in other DBCs. Once you start using it in openpilot it will start failing. For example see this corolla hybrid route 
`075b133b6181e058|2024-01-26--10-39-08`.

**Comment by sshane** [comment]
Done in https://github.com/commaai/opendbc/pull/1246
