### ISSUE TITLE
Hyundai kona 2020 ev no longer detected as supported

### ISSUE THREAD

**Issue by andrewchambers** [commaai/opendbc#1388]
### Describe the bug

My car (Hyundai kona 2020 ev) was detected and working on release 0.9.7, I upgraded to master-ci  and I now get a warning that my car is unsupported and it reverts to dashcam mode.

### Which car does this affect?

Hyundai kona 2020 ev

### Provide a route where the issue occurs

7358a9923f0b36da/00000001--d9a0fbdad6

### openpilot version

4cdc76c

### Additional info

dongle-id=7358a9923f0b36da

![461992028_541877251763358_4828170607194046970_n](https://github.com/user-attachments/assets/070472ca-b594-429a-972e-c2259783f652)
![462537452_1710277209730241_45619270675846030_n](https://github.com/user-attachments/assets/686fed28-eb3e-49e5-a23e-98fc553d2300)

**Comment by sshane** [comment]
Your car was CAN fingerprinting before and was left out of the migration to FPv2. Adding your FW versions here: https://github.com/commaai/opendbc/pull/1387

**Comment by andrewchambers** [comment]
Thanks, really appreciate your work.
