### ISSUE TITLE
Toyota: filter localizer pitch

### ISSUE THREAD

**Issue by sshane** [commaai/opendbc#1476]
Changes too much when accelerating from a stop (~2 deg)

**Comment by gregjhogan** [comment]
Is it accurately tracking the pitch of the device and you want to subtract suspension movement? If yes, maybe you can find a way to quantity this effect, perhaps based on longitudinal jerk.

**Comment by sshane** [comment]
It varies on aEgo mostly

**Comment by sshane** [comment]
https://github.com/commaai/opendbc/pull/1507
