### ISSUE TITLE
HKG unable to engage stock ACC when OP long disabled

### ISSUE THREAD

**Issue by devtekve** [commaai/opendbc#1501]
After https://github.com/sunnypilot/opendbc/commit/68d93be9598d7993b8146d7d398b3fa9dbf20f20 it's impossible to engage OP with long control disabled. It will show the set speed and then as if I hit cancel. 

Route `e1107f9d04dfb1e2/000000ff--17b71931b0/2`

video:
https://github.com/user-attachments/assets/ac3950d0-70a6-4743-9a56-b622550489e7

**Comment by sshane** [comment]
Fixed by https://github.com/commaai/opendbc/pull/1505
