### ISSUE TITLE
Hyundai Azra diesel openpilot ECU firmware and Fingerprint attached

### ISSUE THREAD

**Issue by atawi44** [commaai/opendbc#1525]
It was working with OPKR and Dragonpilot with C2 never worked with openpilot 
After upgrading to 3X It's working only with Dragonpilot  but not with the experimental mod 

 below I attached my fingerprint and ECU firmware for my car,there is a car like it and it's to working with openpilot
But it come to my notice that my car ECU firmware is different harness plug( C)
[values - Copy.txt](https://github.com/user-attachments/files/17905133/values.-.Copy.txt)

**Comment by sshane** [comment]
Can you open a pull request with these changes? Please note your vehicle's trim, model year, region, harness, and whether it has HDA2.
