### ISSUE TITLE
Santa fe 2019

### ISSUE THREAD

**Issue by thabet33** [commaai/opendbc#1572]
### Describe the bug

Dashcam mode car unrecognized
Please help
d7337b1b1b253a32/00000000--84c4329f82

### Which car does this affect?

Hyundai santafe 

### Provide a route where the issue occurs

d7337b1b1b253a32/00000000--84c4329f82

### openpilot version

0.9.7

**Comment by sshane** [comment]
It looks like your car does not have the required features needed to interface with your car; Smart Cruise Control (SCC). I see no radar FW version in your logs. If this is incorrect, please comment back.

**Comment by thabet33** [comment]
thats correct 
dose it mean it will not work ? 
because i see all santa fe is suppuorted in the cars list

**Comment by sshane** [comment]
Yes unfortunately, it will not work. The docs aren't fully accurate for global models as we aim to target the US market. In the US all trims come with SCC so that's why we say it will work with all variants, but your region it seems does not come with SCC on your trim.

**Comment by thabet33** [comment]
Thank you for your time
