### ISSUE TITLE
Question on hyundai_kia_generic.dbc

### ISSUE THREAD

**Issue by gianpyc** [commaai/opendbc#200]
Hi,
I'm analyzing the hyundai_kia_generic DBC and I've a question on the meaning of this BO_
TMU_GW_PE_01

My guess is that the TMU is the telematic ECU, but GW? Is it referred to the gateway? And PE?

Thanks

**Comment by bbsusheelkumar** [comment]
In general, 
TMU is Telematics ECU
GW stands for Gateway
PE stands for Periodic and Event based.

This generally means message is getting transmitted from TMU to GW and its transmission is both periodic and event based.

**Comment by gianpyc** [comment]
Ok, but since the signals are received by the DATC, this means that the frame is sent from the TMU to the DATC passing through the GW?

In HU_DATC_PE_00, HU stands for? In general where I can find the list of the acronyms?

**Comment by bbsusheelkumar** [comment]
In general HU stands for Head Unit i.e.the infotainment of car.

**Comment by gianpyc** [comment]
Ok,
but what is not clear to me in TMU_GW_PE_01 is that you said that the message is sent from TMU to GW, instead in the dbc says that signals are sent from CLU to DATC, where am I wrong? Tnx

**Comment by bbsusheelkumar** [comment]
CLU and DATC in the DBC refers to Nodes. TMU and HU related messages are generally part of CLU node. And it is sent to DATC node through Gateway.
