### ISSUE TITLE
CF_Lkas_Unknown2 signal should be lilttle endian.

### ISSUE THREAD

**Issue by bbsusheelkumar** [commaai/opendbc#206]
https://github.com/commaai/opendbc/blob/4f82d01ebc78109888954d9807d320e3c27896fd/hyundai_kia_generic.dbc#L985

Generally what I observed in my hyundai car is that all the CAN data I received is little endian based.

**Comment by adeebshihadeh** [comment]
Closing this, feel free to submit a PR with this change
