### ISSUE TITLE
Cabana strips CHFFR_METRIC comment

### ISSUE THREAD

**Issue by energee** [commaai/opendbc#21]
Since this directly relates to DBC files, this seems like the right place to log this bug.

When saving to github from cabana: CM_ "CHFFR_METRIC" gets taken out of the file

**Comment by energee** [comment]
I'm not seeing this anymore so either i was wrong or this is fixed.

**Comment by energee** [comment]
Ok on looking at this a little further, there is some odd behaviour. The chffr_metric comment is not being stripped but this is happening:

The format is:

`CM_ "CHFFR_METRIC <message id> <signal> <signal> <value> <value>; CHFFR_METRIC <message id> <signal> <signal> <value> <value>";`

When saved, semicolon is stripped so the line above becomes:

`CM_ "CHFFR_METRIC <message id> <signal> <signal> <value> <value>; CHFFR_METRIC <message id> <signal> <signal> <value> <value>"`

On subsequent saves, quotes get added to the line, so on next save it would look like:

`CM_ "CHFFR_METRIC <message id> <signal> <signal> <value> <value>; CHFFR_METRIC <message id> <signal> <signal> <value> <value>""`

**Comment by andyh2** [comment]
Thanks for the report - should be fixed as of this evening in cabana. Let me know if you have any further issues saving chffr_metrics.
