### ISSUE TITLE
GM and Cadillac powertrains DBC have a wrong OnStar GPS definition

### ISSUE THREAD

**Issue by tmkdev** [commaai/opendbc#293]
This is correct and tested - Conversion from milliarc second to decimal degrees. Signal length is 31 bits not 32. I suspect the first bit on each signal is a validity indicator. 

BO_ 810 TCICOnStarGPSPosition: 8 K73_TCIC
   SG_ GPSLongitude : 38|31@0- (2.77778e-07,0) [0|0] "Degrees" NEO
   SG_ GPSLatitude : 6|31@0- (2.77778e-07,0) [0|0] "Degrees" NEO

**Comment by TheMutley** [comment]
Yes , longitude is 31 and latitude is actually 30. Both bits before these signals are validity bits.

**Comment by adeebshihadeh** [comment]
Closing this, but feel free to reopen as a pull request.
