### ISSUE TITLE
All Mercedes vehicles between 2000-2010

### ISSUE THREAD

**Issue by rnd-ash** [commaai/opendbc#303]
Hi, As part of a project, I've managed to reverse engineer binary files found in Xentry to obtain all this CAN data about all MB vehicles between 2000-2010. The 2 files attached are for the CAN B and C network for my MB model (W203)

I am too lazy to convert them to dbc...so just putting them here if anyone wants to convert them

[203_b.txt](https://github.com/commaai/opendbc/files/5347494/203_b.txt)
[203_c.txt](https://github.com/commaai/opendbc/files/5347495/203_c.txt)

Offsets and Length in these files are specified in bits from the start of the frame

The extractor lists 3 data types:
1. 'B' - Boolean
2. 'I' - Integer
3. 'E' - Enum - Each int value maps to a specific value such as P/R/N/D

You can find the extraction script here:
https://github.com/rnd-ash/MBUX-Port/blob/master/parse_dat_v3.py

**Comment by rnd-ash** [comment]
Unfortuantly, for some values that dont map directly for 1 to 1, there is no way for the extractor script to convert from a raw int to something like Temp C...Below are a couple examples showing that the values don't map directly 1 to 1:
Interior temp is (Raw) / 2 - 40
Fuel usage is (RAW)/2
Exterior temp is Raw-40

**Comment by mitchdetailed** [comment]
I may take this on. :) been a bit lazy with my e55 amg lately

**Comment by adeebshihadeh** [comment]
Feel free to make a PR for this, but I'll close since it's not an issue.
