### ISSUE TITLE
The opendbc/toyota_rav4_2017_pt_generated.dbc needs a modification 

### ISSUE THREAD

**Issue by romybompart** [commaai/opendbc#349]
Hi Guys, I am using cantool for python, when I was trying to upload the dbc to my GUI the bitstruct.error arised with the following error description: 

`bitstruct.Error: "s15" requires -16384 <= integer <= 16383`

So, I noticed the bit length defined in the dbc for these two signals is 15. I changed it to 16 bits, and everything starts to work properly. In general these are the suggested changes: 

```
BO_ 552 ACCELEROMETER: 8 XXX
 SG_ ACCEL_Z : 23|16@0- (1,0) [0|32767] ""  XXX
 SG_ ACCEL_X : 7|16@0- (0.001,0) [-20|20] "m/s2"  XXX
```

**Comment by adeebshihadeh** [comment]
This should be a PR, not an issue.
