### ISSUE TITLE
What do CR_ and CF_ prefixes stand for (i.e. in hyundai_kia_generic.dbc)

### ISSUE THREAD

**Issue by fpetry** [commaai/opendbc#363]
I'm trying to get the semantics of the naming. There doesn't seem to be a common guideline for naming messages and signals.

What do the prefixes stand for, is there an overview somewehere?

**Comment by adeebshihadeh** [comment]
Our issue tracker isn't really for questions. Check out our community discord though. It has a channel specifically for HKGs.

**Comment by fpetry** [comment]
* Would you mind giving a link to the discord?
* What does HKG mean?

**Comment by adeebshihadeh** [comment]
The discord is at https://discord.comma.ai. HKG stands for hyundai, kia, and genesis.
