### ISSUE TITLE
SG_ CR_Mdps_StrAng in hyundai_kia_generic.dbc is incorrect

### ISSUE THREAD

**Issue by andresv** [commaai/opendbc#384]
It is `i16` signal so max cannot be `65535` here:

```
SG_ CR_Mdps_StrAng : 24|16@1- (1,0) [0|65535] "" XXX
```
https://github.com/commaai/opendbc/blob/master/hyundai_kia_generic.dbc#L1551

**Comment by adeebshihadeh** [comment]
See #383.
