### ISSUE TITLE
GPS Coords in gm_global_a_powertrain are wrong

### ISSUE THREAD

**Issue by collin80** [commaai/opendbc#411]
The signals should be 31 bit signed big endian integers to turn them into milliarcseconds. They are currently 32 bit big endian unsigned signals. This won't work for those of us with negative longitude which is how I found the problem. 

I tested this on a 2019 Equinox. I'm not sure if this error persists across all other GLOBAL-A cars or if the Equinox is special.

Also, a conversion factor of 2.77778e-07 for lat/long would turn them into degrees which is far easier to use than milli-arcseconds.

**Comment by adeebshihadeh** [comment]
Feel free to make a PR for this.
