### ISSUE TITLE
generator: nested imports

### ISSUE THREAD

**Issue by belm0** [commaai/opendbc#415]
Currently, it seems that only the top level input to the generator can have imports.  It would be useful if imported files could themselves contain imports.

I could have used this when refactoring the honda files to share common definitions among models based on the Fit platform.

wanted
------
chain of imports: `honda_hrv_touring_2019_can -> _honda_fit_2018 -> _honda_2017 / _comma`

current situation
--------------
the top-level file must import transitive dependencies explicitly, in the correct order:
```
CM_ "IMPORT _honda_fit_2018.dbc";
CM_ "IMPORT _honda_2017.dbc";
CM_ "IMPORT _comma.dbc";
```

**Comment by adeebshihadeh** [comment]
I'm not sure the complexity of nested imports is really worth it. Recently, the Toyota DBCs were cleaned up and merged into only three different DBCs. We're working on a similar cleanup for Honda now.
