### ISSUE TITLE
 Misplaced inline comment

### ISSUE THREAD

**Issue by ryleymcc** [commaai/opendbc#460]
https://github.com/commaai/opendbc/blob/c8d7cb4cc6c56f4595afdfca68b1ef1ad5f29aa3/can/dbc_template.cc#L12 There seems to be an extra '/' in the line. Found it while trying to port some code.

**Comment by adeebshihadeh** [comment]
The `//` is for integer division in python. The code executed in those blocks is python, and the template is rendered by jinja2.
