### ISSUE TITLE
Honda DBC cleanup

### ISSUE THREAD

**Issue by sshane** [commaai/opendbc#523]
- [ ] See if `LAT_ACCEL` under `KINEMATICS` on 145 is also available on 148 for cars using 145. The LAT_ACCEL signal is defined in the same location in the message
- [ ] Fix duplicate gear signals defined
- [ ] A lot of these messages are common in bosch vehicles, possible unify:
  - [ ] DOORS_STATUS
  - [ ] STANDSTILL
  - [ ] GEARBOX
  - [ ] GAS_PEDAL_2

**Comment by vanillagorillaa** [comment]
I believe that both kinematics messages are the same and can have the same signal definitions. Verified with an ILX last night which uses 145

**Comment by sshane** [comment]
Closing for #496
