### ISSUE TITLE
Toyota: understand ACC command signals

### ISSUE THREAD

**Issue by sshane** [commaai/opendbc#644]
There's a bit in ACC_CONTROL that gets set to 1 (`SG_ MYSTERY_BIT : 28|1@0+ (1,0) [0|1] "" XXX`) whenever the car's stock system starts requesting brake when aEgo is generally high, figure out if that does anything at all for increasing response of any kind.

ACCEL_CMD_ALT also seems to hold the future acceleration request and is different depending on if there's a lead or not (with lead it matches exactly, without it goes to the future acceleration request immediately.)
![Screenshot from 2022-06-18 20-02-10](https://user-images.githubusercontent.com/25857203/174468688-36b9d516-257c-4886-81ed-a58ec663b371.png)
![Screenshot from 2022-06-18 20-04-27](https://user-images.githubusercontent.com/25857203/174468690-46bfa3c4-8e98-4d1a-a2c0-d9f1ed06ec88.png)

**Comment by cydia2020** [comment]
The first one could be "Status of the Bruise Brake Control Decision / OFF or ON" indicated in some diagnostic tools, have you checked with techstream?

As for the second one, it could be "Driving Support ECU Target Acceleration (m/s^2, ft/s^2, g)"
