### ISSUE TITLE
Docker build fails on arm

### ISSUE THREAD

**Issue by series8217** [commaai/opendbc#663]
There are some issues preventing the Dockerfile from building on `arm`, because wheels aren't available for all the Python dependencies, and the Dockerfile doesn't set up an environment capable of building python modules from source.

a) The pinned version of pycapnp (1.0.0) in opendbc's `requirements.txt` has a [bug](https://github.com/capnproto/pycapnp/issues/240#issuecomment-797258605)causing installation to fail. A workaround is to install pkgconfig separately before trying to install pycapnp. Alternatively, the bug is fixed in 1.1.0 ([changelog here](https://pypi.org/project/pycapnp/1.1.0/)). So changing requirements.txt to have pycapnp==1.1.0 is probably a better solution.

b) building pycapnp from source requires having libcapnp available. pycapnp's setup.py will try to build capnproto-c++ from source, but it fails due to cmake not being installed in the docker container.

I'm working on a fix, which is currently looking like:
1) Bump pycapnp from 1.0.0 to 1.1.0. I don't see any breaking changes in the [changelog](https://pypi.org/project/pycapnp/1.1.0/) but I'm also pretty new to this project so I could be missing something.
2) Adding cmake so pycapnp can build libcapnp as required.

Here is the failure in the build log for opendbc's Dockerfile. Docker version is `20.10.17, build 100c701`:

```Step 10/19 : RUN pip install --no-cache-dir -r /tmp/requirements.txt
 ---> Running in ce2fc87cbf2d
Collecting Cython==0.29.14
  Downloading Cython-0.29.14.tar.gz (2.1 MB)
Collecting flake8==3.7.9
  Downloading flake8-3.7.9-py2.py3-none-any.whl (69 kB)
Collecting Jinja2==3.0.3
  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)
Collecting numpy==1.21.0
  Downloading numpy-1.21.0.zip (10.3 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pycapnp==1.0.0
  Downloading pycapnp-1.0.0.tar.gz (528 kB)
    ERROR: Command errored out with exit status 1:
     command: /root/.pyenv/versions/3.8.10/bin/python3.8 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5kbwmb_p/pycapnp_e8e8914b3bdf4ee590be2773883c39af/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5kbwmb_p/pycapnp_e8e8914b3bdf4ee590be2773883c39af/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1sbqaq8s
         cwd: /tmp/pip-install-5kbwmb_p/pycapnp_e8e8914b3bdf4ee590be2773883c39af/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5kbwmb_p/pycapnp_e8e8914b3bdf4ee590be2773883c39af/setup.py", line 12, in <module>
        import pkgconfig
    ModuleNotFoundError: No module named 'pkgconfig'
    ----------------------------------------
```

This bug [also affects the build of panda](https://github.com/commaai/panda/issues/984) since Dockerfile.panda needs to build opendbc.

**Comment by adeebshihadeh** [comment]
We've fixed the ARM build of openpilot, so this should work now too.
