### ISSUE TITLE
Large signal values are not parsed correctly

### ISSUE THREAD

**Issue by martinl** [commaai/opendbc#703]
Large signal values (eg 57174604644354) are not parsed correctly after https://github.com/commaai/opendbc/commit/859fea7ded706516f4b963218a3c9cf543f39c2a

Here is a test and more information for one case with Subaru https://github.com/commaai/opendbc/pull/702

**Comment by martinl** [comment]
It initially looked like integer overflow but maybe something else:

<img width="455" alt="Screenshot 2022-09-05 at 19 06 42" src="https://user-images.githubusercontent.com/148686/188486995-752e9ca4-7f13-46a2-b3a8-006a2ecbf6b9.png">

**Comment by adeebshihadeh** [comment]
Fixed in #702?

**Comment by adeebshihadeh** [comment]
Is this still an issue?

**Comment by martinl** [comment]
Fixed by #702
