### ISSUE TITLE
Subaru: DOOR_OPEN_FL and DOOR_OPEN_FR are flipped

### ISSUE THREAD

**Issue by Moodkiller** [commaai/opendbc#704]
Car: Subaru Impreza 2017 (RHD model)

Test case: Stopped, passenger (situated on the Left), got out of the car, FR counter tripped. 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/11341653/188593310-79ba7b08-5bdc-4d56-809b-03214509ea4e.png">

Route: `e072a2834758d311|2022-09-06--06-28-47--33`

**Comment by adeebshihadeh** [comment]
I'd merge a PR to fix, but the flipping doesn't affect openpilot.
