### ISSUE TITLE
Source for GM PT CAN Traces/Logs?

### ISSUE THREAD

**Issue by GTO2013** [commaai/opendbc#713]
Hi,
I am currently working on a custom cluster for an LS3 swap (https://www.youtube.com/watch?v=v9tjfbJrVV4). 
I dont have the engine or ECU running yet, but I would like to work on the CAN communication on those cold rainy days.
Are there any logs/traces available, especially for the GM PT CAN stuff?

Thanks for your help,
Robin

**Comment by adeebshihadeh** [comment]
This repo only contains the DBC files.
