### ISSUE TITLE
List of Compatible Vehicles

### ISSUE THREAD

**Issue by Edwardius** [commaai/opendbc#740]
Hello, 

I was wondering if there is an updated list of all the vehicles that commaai has successfully reverse-engineered. 

Thanks!

**Comment by incognitojam** [comment]
openpilot supported vehicles are found in [CARS.md](https://github.com/commaai/openpilot/blob/master/docs/CARS.md), or the respective car brand folders `values.py` [in openpilot](https://github.com/commaai/openpilot/tree/master/selfdrive/car).
