### ISSUE TITLE
need for information about openbc

### ISSUE THREAD

**Issue by monikamishra-54** [commaai/opendbc#772]
Hello,
We just need one information regarding OBD2 (we have OBD2 device ELM25K80) when we connect our app from this device we get only engine specific code but we need ABS, body, suspension, etc data from OBD2. Is your repository help in this case or can you provide me some link where we can get some help.
Thanks!

**Comment by adeebshihadeh** [comment]
Closing since this is not an issue. Check out our [community discord](https://discord.comma.ai) server for discussions like this instead.
