### ISSUE TITLE
Remove dependence on cereal

### ISSUE THREAD

**Issue by adeebshihadeh** [commaai/opendbc#825]
Replace the CANParser's inputs that use `cereal::CanData`; will need to be done carefully to avoid a large hit to performance.

**Comment by adeebshihadeh** [comment]
@deanlee want to look into this? I'm thinking we make or use an existing struct from opendbc that represents a CAN message, then we write a fast cython function in openpilot to go from cereal's CAN struct to opendbc's struct

**Comment by deanlee** [comment]
sure,working on this
