### ISSUE TITLE
CAN parser: assert signals exist

### ISSUE THREAD

**Issue by sshane** [commaai/opendbc#869]
We already assert messages exist, but signals are unchecked. This was the cause of https://github.com/commaai/openpilot/issues/28404, `CRUISE_INACTIVE` inside `SCC_CONTROL` doesn't exist, but it never complained or gave a warning before. @deanlee see any reason not to check signals too?

Code to reproduce:

```python
from opendbc.can.parser import CANParser
cp = CANParser('hyundai_canfd', [("ANYTHING123", "SCC_CONTROL")], [("SCC_CONTROL", 50)], 2)
```

**Comment by sshane** [comment]
Related to https://github.com/commaai/opendbc/issues/500

**Comment by adeebshihadeh** [comment]
This should absolutely have an assert.

**Comment by sshane** [comment]
The signal option name is passed all the way to the cpp code, which only loops through the DBC signals to find any matches, it doesn't check it finds one

https://github.com/commaai/opendbc/blob/e51a78721d99eac223f02cd9b993824712855952/can/parser.cc#L144-L150

**Comment by deanlee** [comment]
how about check it in cython? https://github.com/commaai/opendbc/pull/870
