### ISSUE TITLE
CAN Packer: undefined behavior when not setting a signal

### ISSUE THREAD

**Issue by sshane** [commaai/opendbc#882]
While looking at https://github.com/commaai/openpilot/pull/27785 I noticed that the CAN packer takes on different behavior depending on if you define a signal to 0, or leave it out of the dictionary. if you define it to 0, it will take the correct offset and scaling into account, but if you don't it will just set the bytes to `0x00`. This can lead to unintended behavior as you expect them to produce the same behavior

reproduction:

```python
from opendbc.can.packer import CANPacker
packer = CANPacker('hyundai_canfd')
packer.make_can_msg('SCC_CONTROL', 0, {'VSetDis': 0})[2][16]
Out[59]: 0
packer.make_can_msg('SCC_CONTROL', 0, {'VSetDis': 0, 'aReqValue': 0})[2][16]
Out[61]: 255
```

openpilot issue: https://github.com/commaai/openpilot/issues/28822

**Comment by sshane** [comment]
@deanlee what do you think is better, in cython adding all signals with 0 value defaults, or handle in packer.cc?

**Comment by deanlee** [comment]
It might be better to implement it inside packer.cc.
