### ISSUE TITLE
File .dbc for Hyundai Ioniq 5?

### ISSUE THREAD

**Issue by tuan97ta** [commaai/opendbc#948]
I am looking file .dbc for the control and read information from Hyundai Ioniq 5 car ? 
I found [hyundai_kia_generic.dbc](https://github.com/commaai/opendbc/blob/master/hyundai_kia_generic.dbc) , but I don't know if It can use for Hyundai Ioniq 5 ?

**Comment by sshane** [comment]
Try https://github.com/commaai/opendbc/blob/master/hyundai_canfd.dbc
